import '../styles/globals.css';
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google';

const roboto = Roboto({ subsets: ['latin'], weight: ['100', '400', '700'] });

export const metadata: Metadata = {
  title: 'Animes',
  description: 'Generated by Jonatas Rosa Moura',
  authors: [{ name: 'Jonatas Rosas Moura', url: 'https://venerable-cuchufli-099677.netlify.app/' }],
  category: 'Anime',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
