import '../styles/globals.css';
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google';

import { Header } from '@/components/Header';

const roboto = Roboto({ subsets: ['latin'], weight: ['100', '400', '700'] });

export const metadata: Metadata = {
  title: 'Anime catalog',
  description: 'Generated by Jonatas Rosa Moura',
  authors: [{ name: 'Jonatas Rosas Moura', url: 'https://venerable-cuchufli-099677.netlify.app/' }],
  category: 'Anime',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${roboto.className}
          bg-background
          text-textLight
          w-full
          m-auto
          md:max-w-screen-2xl
        `}
      >
        <Header />
        <section className="bg-primary  rounded h-[85vh] overflow-y-scroll">
          {children}
        </section>
      </body>
    </html>
  );
}
